### PR TITLE
Simplify Github Actions CI

### PR DESCRIPTION
**Pull request by jackkoenig**
WIP

### CODE REVIEW

**Review by chick — APPROVED** [review]
That's a very nice simplification

**Comment by jackkoenig** [comment]
A lot of the code before was dealing with using a Docker image for dependencies like Verilator; none of which are needed by this repo. I suspect we'll want to refer back to it if we were to move Chisel or FIRRTL to Github Actions.

That being said, we might as well make it as simple as possible for Treadle since we have that luxury 🙂

**Comment by jackkoenig** [comment]
Also some of it was for building dependencies which becomes unnecessary with the auto SNAPSHOT publishing

**Comment by jackkoenig** [comment]
@Mergifyio backport 1.3.x 1.2.x

**Pull request merged**
