### PR TITLE
Clean up Treadle: TestHarness

### PR DESCRIPTION
**Pull request by chick**
- Change all possible printlns into logger.<appropriate-level>
- Create a TreadleTestHarness
  - Make cleaner API for running tests in Treadle
  - Make all tests involving a tester to run in a Logger.makeScope
-

### CODE REVIEW

**Comment by chick** [comment]
@seldridge I don't really need a full review of this.
This is the first step to making Treadle's tests clean and silent. I think I have a reasonable pattern here.
 I am hoping you can take a quick look and see if I am not using new Stage stuff the way it should be. 
Next step would be to go through all tests refactoring Tester creation and printlns -> logger.<x>

**Comment by chick** [comment]
This is a mostly a cosmetic change.
- Almost every treadle tester in tests has been changed to use a TreadleTestHarnesss
  - sets up logging environment correctly
  - calls TreadleTester#finish
- Test no longer emit any output, printlns have been removed or changed to logger statements

**Comment by jackkoenig** [comment]
@Mergifyio backport 1.3.x

**Comment by jackkoenig** [comment]
@Mergifyio backport 1.3.x 1.2.x

**Comment by jackkoenig** [comment]
I meant to do the second backport command on https://github.com/freechipsproject/treadle/pull/267 lol, whoops.

**Pull request merged**
